apiVersion: apps/v1
kind: Deployment
metadata:
  name: catnip-deployment
  labels:
    app: catnip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catnip
  template:
    metadata:
      labels:
        app: catnip
    spec:
      containers:
      - name: catnip
        image: docker.io/ylihit/catnip:v1.1
        ports:
        - name: http
          containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: "ok-service-catnip"
spec:
  selector:
    app: catnip
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
